### ISSUE TITLE
Issue Creating Learnings in SF Almond

### ISSUE THREAD

**Issue by erianabutler** [forcedotcom/almond#51]
I have followed your HOWTO in both Production and UAT. The problem I am having is that when I am creating an new Learning, the system circumvents the SELECT LEARNING RECORD TYPE page and immediately goes to the NEW LEARNING page that places attributes on the Learning that we were supposed to have entered in the previous step. 

I have system developer privileges to be able to see the Select Learning Type page, I can also see in the LEARNING object that you have the ability to create QUIZ, RESOURCE, TASK Record Types....I also know that the Page Layout Assignment has been assigned to my Profile type. Any ideas?

**Comment by jonathanrico** [comment]
@erianabutler , 

This usually means that your user doesn't have access to the different record types of the Learning Object. Even if you're a sys admin you still need to make these record types visible through your profile or a permission set. I've provided some details around this in the setup guide. 

My recommendation is to create a separate permission set that just gives access to the learning record types and assign this permission on top of the package permission set (LMS Admin or LMS User). Let me know if you still have any questions, if possible, let's continue this thread in the success community since it's very likely that this is a configuration issue : https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009MMT
